spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=personmanagementdb;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
