server:
  port: 8095
management:
  endpoints:
    web:
      exposure:
         include: "*"
spring:
  zipkin:
    base-url: http://localhost:9411/
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=PersonManagementDB;encrypt=true;trustServerCertificate=true;
    username: to-be-overwritten-by-vault-value
    password: to-be-overwritten-by-vault-value
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2017Dialect
    show-sql: true
