spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=PersonManagementDB
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2017Dialect
    show-sql: true
