server:
  port: 8097

spring:
  cloud:
    gateway:
      routes:
      - id: travel-management-server
        uri: http://localhost:8096/
        predicates:
        - Path=/travel/**
      - id: person-management-server
        uri: http://localhost:8095/
        predicates:
        - Path=/person/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


    loadbalancer:
      ribbon:
        enabled: false
        
  main:
    web-application-type: reactive

logging:
  level: debug
