server:
  port: 8097

spring:
  cloud:
    gateway:
      routes:
      - id: person-management-server
        uri: lb://person-management
        predicates:
        - Path=/PersonManagement/**
      - id: travel-management-server
        uri: lb://travels-management
        predicates:
        - Path=/TravelManagement/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


    loadbalancer:
      ribbon:
        enabled: false
  main:
    web-application-type: reactive

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
